"""Export the vendored filled-contour catalog for both web views.

``glyphs.js`` feeds the layered Canvas view: complete SVG paths plus the
per-glyph speeds and trail lengths in ``glyph-motion.json``.
``svg-preview/glyphs.js`` is the explorer's unchanged copy of
``catalog/catalog.json``. Native ports use the same SVG catalog; export those
separately with ``python export_native_glyphs.py``:

    python export_glyphs.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CATALOG = ROOT / "catalog/catalog.json"
MOTION = ROOT / "glyph-motion.json"
HEADER = "Generated by export_glyphs.py from the current SVG catalog."
BROWSER_HEADER = "Generated from the current Smythe contour catalog."


def _catalog() -> dict:
    return json.loads(CATALOG.read_text(encoding="utf-8"))


def _payload() -> dict:
    catalog = _catalog()
    motion = json.loads(MOTION.read_text(encoding="utf-8"))
    count = len(catalog["glyphs"])
    if not motion["count"] == len(motion["speeds"]) == len(motion["trails"]) == count:
        raise ValueError("glyph-motion.json needs one speed and one trail per catalog glyph")
    return {
        "canvas": catalog["canvas"], "version": catalog["version"],
        "catalog_sha256": catalog["catalog_sha256"],
        "paths": [glyph["paths"] for glyph in catalog["glyphs"]],
        "speeds": motion["speeds"],
        "trails": motion["trails"],
    }


def _write(destination: Path, content: str) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {destination} ({destination.stat().st_size} bytes)")


def main() -> None:
    compact = json.dumps(_payload(), separators=(",", ":"))
    _write(
        ROOT / "glyphs.js",
        f"// {HEADER} Do not edit by hand.\n"
        f"const GLYPHS={compact};\n",
    )
    browser = json.dumps(_catalog(), separators=(",", ":"))
    _write(
        ROOT / "svg-preview/glyphs.js",
        f"// {BROWSER_HEADER}\n"
        f"globalThis.SVG_GLYPHS = {browser};\n",
    )


if __name__ == "__main__":
    main()
